logging:
  level:
    root: info
    me.liuwj.ktorm: debug
server:
  port: 8081
spring:
  application:
    name: ktProject
  datasource:
    url: jdbc:mysql://localhost:3306/test?&serverTimezone=Hongkong
    username: root
    password: csk110110
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    port: 6379
    timeout: 100ms

